### ISSUE TITLE
Is there a script to extract point cloud and image in ROS2?

### ISSUE THREAD

**Issue by ProForver** [MikaelSkog/tmva4d-ros-extract#1]
I am using the latest version of Hugin radar, but the software of this radar is released based on ROS2. Do you have a script based on ROS2? Thank you very much!

**Comment by MikaelSkog** [comment]
Would you like to extract point clouds during data collection, or from recorded data such as ROS bags or MCAP files? Unfortunately, the script is not fast enough to process live ROS data feeds.

Please note that the point cloud extractor script is designed to extract PCD files from recorded ROS messages (e.g., bag files), with point coordinates resulting from projections to camera frames. Is that what you want to do?

**Comment by ProForver** [comment]
Thank you for your reply!
I don't need to extract point clouds during data collection. I want to extract Radar PCD files from recorded ROS messages(.mcap files)

**Comment by MikaelSkog** [comment]
I don't have any scripts for extracting PCD files from .mcap files. What you can do is the following:

1. Upload each of your .mcap files to [https://app.foxglove.dev](https://app.foxglove.dev) as recordings, then export your recordings as .bag files.
2. Set up a ROS1 environment.
3. Reindex each of your bag files using `rosbag reindex <bag_file_name>`.
4. If you just want to save the point clouds directly from your bag files, run `rosrun pcl_ros bag_to_pcd <input_file.bag> <topic> <output_directory>`. If you want to save them with values obtained from projecting the point clouds to the camera frame, just run replay your bag files using `rosbag play --clock --rate=0.02 <bag_file_name>` and follow my instructions provided on this repository.

**Comment by ProForver** [comment]
Thank you for your detailed reply, which has been helpful to me. I wish you all the best in the future and look forward to our next communication！
